name: superdeclarative_ffmpeg
version: 0.1.0
description: Communicates with the FFMPEG CLI.
homepage: https://github.com/matthew-carroll/superdeclarative_ffmpeg

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation: ^4.1.0

dev_dependencies:
  test: ^1.17.12
  build_runner: ^2.1.2
  json_serializable: ^5.0.1